// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAdRV2PnMuf8e1bfVu8LzQUE7XIwI1seE',
    appId: '1:52736760116:web:4cd7d249582ad7895fed61',
    messagingSenderId: '52736760116',
    projectId: 'masjid-connect-cd298',
    authDomain: 'masjid-connect-cd298.firebaseapp.com',
    storageBucket: 'masjid-connect-cd298.firebasestorage.app',
    measurementId: 'G-SSP7NEW4CG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC160F6JFCF16l25_DlOeqhn1Ygk-qvx58',
    appId: '1:52736760116:android:bcc223644d5b271a5fed61',
    messagingSenderId: '52736760116',
    projectId: 'masjid-connect-cd298',
    storageBucket: 'masjid-connect-cd298.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBzTayXR81-mGHconWGjYDU0SdYaHukPE',
    appId: '1:52736760116:ios:b90c1fb6c97a48635fed61',
    messagingSenderId: '52736760116',
    projectId: 'masjid-connect-cd298',
    storageBucket: 'masjid-connect-cd298.firebasestorage.app',
    iosBundleId: 'com.example.masjidConnectApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBzTayXR81-mGHconWGjYDU0SdYaHukPE',
    appId: '1:52736760116:ios:b90c1fb6c97a48635fed61',
    messagingSenderId: '52736760116',
    projectId: 'masjid-connect-cd298',
    storageBucket: 'masjid-connect-cd298.firebasestorage.app',
    iosBundleId: 'com.example.masjidConnectApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAdRV2PnMuf8e1bfVu8LzQUE7XIwI1seE',
    appId: '1:52736760116:web:c6a4c51351de47d05fed61',
    messagingSenderId: '52736760116',
    projectId: 'masjid-connect-cd298',
    authDomain: 'masjid-connect-cd298.firebaseapp.com',
    storageBucket: 'masjid-connect-cd298.firebasestorage.app',
    measurementId: 'G-5K3K2KS9MY',
  );

}