// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2qrcrySKSlOOgfFvdDVJTLZc62nGbaQo',
    appId: '1:1005795988882:web:97217ba18883df7e781d4b',
    messagingSenderId: '1005795988882',
    projectId: 'masjid-connect-33bb3',
    authDomain: 'masjid-connect-33bb3.firebaseapp.com',
    storageBucket: 'masjid-connect-33bb3.firebasestorage.app',
    measurementId: 'G-M7EE2PXYFK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDch_YDfIiZ97zAoiNi3TJV0KQYj19DzXE',
    appId: '1:1005795988882:android:d78fc872f48de8e5781d4b',
    messagingSenderId: '1005795988882',
    projectId: 'masjid-connect-33bb3',
    storageBucket: 'masjid-connect-33bb3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCvNM0SclZ1dBrUyR0JAgvGvH1A9XPxMY',
    appId: '1:1005795988882:ios:d4e4ea1ecb45397c781d4b',
    messagingSenderId: '1005795988882',
    projectId: 'masjid-connect-33bb3',
    storageBucket: 'masjid-connect-33bb3.firebasestorage.app',
    iosBundleId: 'com.example.masjidConnectApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCvNM0SclZ1dBrUyR0JAgvGvH1A9XPxMY',
    appId: '1:1005795988882:ios:d4e4ea1ecb45397c781d4b',
    messagingSenderId: '1005795988882',
    projectId: 'masjid-connect-33bb3',
    storageBucket: 'masjid-connect-33bb3.firebasestorage.app',
    iosBundleId: 'com.example.masjidConnectApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2qrcrySKSlOOgfFvdDVJTLZc62nGbaQo',
    appId: '1:1005795988882:web:23891d56ff42878f781d4b',
    messagingSenderId: '1005795988882',
    projectId: 'masjid-connect-33bb3',
    authDomain: 'masjid-connect-33bb3.firebaseapp.com',
    storageBucket: 'masjid-connect-33bb3.firebasestorage.app',
    measurementId: 'G-B6MKLGXKKR',
  );

}